name: Publish Docker Image

on:
  push:
    branches: ['podaj-branch']

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          #Należy wypełnić zmienne środowiskowe w ustawieniach repozytorium
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Debug Build Cache
        #Sprawdzamy czy cache działa
        run: docker buildx imagetools inspect {nazwa-konta}/{nazwa-repozytorium}:buildcache

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: {nazwa-konta}/{nazwa-repozytorium}
          cache-from: type=registry,ref={nazwa-konta}/{nazwa-repozytorium}:buildcache
          cache-to: type=registry,ref={nazwa-konta}/{nazwa-repozytorium},mode=max

      - name: Deploy (trigger server script)
        uses: appleboy/ssh-action@v1.0.0
        with:
          #Należy wypełnić zmienne środowiskowe w ustawieniach repozytorium
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            echo "Logging in to Docker Hub..."
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            echo "Running server-side deploy script..."
            #Here you can put your server-side deploy script for example
            docker pull ...
            docker run ...
            docker exec ...
            supervisorctl restart ...
