export default function GameBanner() {
    return (
        <div className={'flex justify-center'}>
            <svg xmlns="http://www.w3.org/2000/svg" width="600" height="150">
                <line
                    x1="80"
                    y1="50"
                    x2="80"
                    y2="100"
                    stroke="var(--line-color)"
                    strokeWidth="2"
                />
                <circle
                    cx="80"
                    cy="40"
                    r="10"
                    fill="none"
                    stroke="var(--line-color)"
                    strokeWidth="2"
                />
                <line
                    x1="80"
                    y1="60"
                    x2="60"
                    y2="80"
                    stroke="var(--line-color)"
                    strokeWidth="2"
                />
                <line
                    x1="60"
                    y1="80"
                    x2="50"
                    y2="70"
                    stroke="var(--line-color)"
                    strokeWidth="2"
                />
                <line
                    x1="80"
                    y1="60"
                    x2="100"
                    y2="80"
                    stroke="var(--line-color)"
                    strokeWidth="2"
                />
                <line
                    x1="80"
                    y1="100"
                    x2="70"
                    y2="120"
                    stroke="var(--line-color)"
                    strokeWidth="2"
                />
                <line
                    x1="80"
                    y1="100"
                    x2="90"
                    y2="120"
                    stroke="var(--line-color)"
                    strokeWidth="2"
                />
                <line
                    x1="520"
                    y1="50"
                    x2="520"
                    y2="100"
                    stroke="var(--line-color)"
                    strokeWidth="2"
                />
                <circle
                    cx="520"
                    cy="40"
                    r="10"
                    fill="none"
                    stroke="var(--line-color)"
                    strokeWidth="2"
                />
                <line
                    x1="520"
                    y1="60"
                    x2="540"
                    y2="80"
                    stroke="var(--line-color)"
                    strokeWidth="2"
                />
                <line
                    x1="540"
                    y1="80"
                    x2="550"
                    y2="70"
                    stroke="var(--line-color)"
                    strokeWidth="2"
                />
                <line
                    x1="520"
                    y1="60"
                    x2="500"
                    y2="80"
                    stroke="var(--line-color)"
                    strokeWidth="2"
                />
                <line
                    x1="520"
                    y1="100"
                    x2="510"
                    y2="120"
                    stroke="var(--line-color)"
                    strokeWidth="2"
                />
                <line
                    x1="520"
                    y1="100"
                    x2="530"
                    y2="120"
                    stroke="var(--line-color)"
                    strokeWidth="2"
                />
                <text
                    x="280"
                    y="60"
                    fontFamily="Arial, sans-serif"
                    fontSize="28"
                    fill="var(--text-color)"
                    textAnchor="middle"
                >
                    Empirebuilder
                </text>
                <text
                    x="280"
                    y="90"
                    fontFamily="Arial, sans-serif"
                    fontSize="16"
                    fill="var(--text-color)"
                    textAnchor="middle"
                >
                    An Adventurer is You!
                </text>
            </svg>
        </div>
    );
}
